name: Actions Workflow

on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:  
      - name: List Files
        run: |
          pwd
          ls -a 
      - name: Checkout
        uses: vikash-verma-profile/GithubActionTest@main
      - name: List Files After Checkout
      
      - name: Simple application
        id: greet
        uses: vikash-verma-profile/test-web-app@main 
        with:
           who-to-greet: Ram
      - name: Log Greeting time
        run: echo "${{steps.greet.outputs.time}}"
       
      
